id: PF26B8144
initial_creation_type: input
source_metadata:
  title: Bodhasāra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Jennifer Cover
  contribution to GRETIL: Jennifer Cover
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:55:54.888260'
last_modified_at: '2022-03-09T14:55:54.888274'
